ignoredBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - protobufjs
onlyBuiltDependencies:
  - esbuild
overrides:
  '@firebasegen/default-connector': link:dataconnect-generated/js/default-connector
  '@firebasegen/pib-connector': link:dataconnect-generated/js/pib-connector
