"""
✨ `BusinessProfile_KeyOutput` returns the primary key fields of table type `BusinessProfile`.

It has the same format as `BusinessProfile_Key`, but is only used as mutation return value.
"""
scalar BusinessProfile_KeyOutput
"""
✨ `LLMKey_KeyOutput` returns the primary key fields of table type `LLMKey`.

It has the same format as `LLMKey_Key`, but is only used as mutation return value.
"""
scalar LLMKey_KeyOutput
"""
✨ `PartnerPreferences_KeyOutput` returns the primary key fields of table type `PartnerPreferences`.

It has the same format as `PartnerPreferences_Key`, but is only used as mutation return value.
"""
scalar PartnerPreferences_KeyOutput
"""
✨ `Profile_KeyOutput` returns the primary key fields of table type `Profile`.

It has the same format as `Profile_Key`, but is only used as mutation return value.
"""
scalar Profile_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ `Workspace_KeyOutput` returns the primary key fields of table type `Workspace`.

It has the same format as `Workspace_Key`, but is only used as mutation return value.
"""
scalar Workspace_KeyOutput
"""
✨ `WorkspaceInvitation_KeyOutput` returns the primary key fields of table type `WorkspaceInvitation`.

It has the same format as `WorkspaceInvitation_Key`, but is only used as mutation return value.
"""
scalar WorkspaceInvitation_KeyOutput
"""
✨ `WorkspaceMember_KeyOutput` returns the primary key fields of table type `WorkspaceMember`.

It has the same format as `WorkspaceMember_Key`, but is only used as mutation return value.
"""
scalar WorkspaceMember_KeyOutput
"""
✨ `WorkspaceUser_KeyOutput` returns the primary key fields of table type `WorkspaceUser`.

It has the same format as `WorkspaceUser_Key`, but is only used as mutation return value.
"""
scalar WorkspaceUser_KeyOutput
"""
✨ Generated data input type for table 'BusinessProfile'. It includes all necessary fields for creating or upserting rows into table.
"""
input BusinessProfile_Data {
  """
  ✨ Generated from Field `BusinessProfile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `BusinessProfile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `BusinessProfile`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `BusinessProfile`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `BusinessProfile`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `BusinessProfile`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `BusinessProfile`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `BusinessProfile`.`descriptionEmbedding` of type `Vector`
  """
  descriptionEmbedding: Vector
  """
  ✨ `_embed` server value variant of `descriptionEmbedding` (✨ Generated from Field `BusinessProfile`.`descriptionEmbedding` of type `Vector`)
  """
  descriptionEmbedding_embed: Vector_Embed
  """
  ✨ Generated from Field `BusinessProfile`.`employeeCount` of type `Int`
  """
  employeeCount: Int
  """
  ✨ Generated from Field `BusinessProfile`.`industry` of type `String`
  """
  industry: String
  """
  ✨ `_expr` server value variant of `industry` (✨ Generated from Field `BusinessProfile`.`industry` of type `String`)
  """
  industry_expr: String_Expr
  """
  ✨ Generated from Field `BusinessProfile`.`location` of type `String`
  """
  location: String
  """
  ✨ `_expr` server value variant of `location` (✨ Generated from Field `BusinessProfile`.`location` of type `String`)
  """
  location_expr: String_Expr
  """
  ✨ Generated from Field `BusinessProfile`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `BusinessProfile`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `BusinessProfile`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `BusinessProfile`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `BusinessProfile`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `BusinessProfile`.`website` of type `String`
  """
  website: String
  """
  ✨ `_expr` server value variant of `website` (✨ Generated from Field `BusinessProfile`.`website` of type `String`)
  """
  website_expr: String_Expr
  """
  ✨ Generated from Field `BusinessProfile`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `BusinessProfile`.`workspaceId` of type `UUID!`)
  """
  workspaceId_expr: UUID_Expr
}
"""
✨ Generated filter input type for table 'BusinessProfile'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input BusinessProfile_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [BusinessProfile_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: BusinessProfile_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [BusinessProfile_Filter!]
  """
  ✨ Generated from Field `BusinessProfile`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`descriptionEmbedding` of type `Vector`
  """
  descriptionEmbedding: Vector_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`employeeCount` of type `Int`
  """
  employeeCount: Int_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`industry` of type `String`
  """
  industry: String_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`location` of type `String`
  """
  location: String_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`website` of type `String`
  """
  website: String_Filter
  """
  ✨ Generated from Field `BusinessProfile`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID_Filter
}
"""
✨ Generated first-row input type for table 'BusinessProfile'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input BusinessProfile_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [BusinessProfile_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: BusinessProfile_Filter
}
"""
✨ Generated key input type for table 'BusinessProfile'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input BusinessProfile_Key {
  """
  ✨ Generated from Field `BusinessProfile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `BusinessProfile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'BusinessProfile'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input BusinessProfile_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: BusinessProfile_Filter
}
"""
✨ Generated order input type for table 'BusinessProfile'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input BusinessProfile_Order {
  """
  ✨ Generated from Field `BusinessProfile`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`descriptionEmbedding` of type `Vector`
  """
  descriptionEmbedding: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`employeeCount` of type `Int`
  """
  employeeCount: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`industry` of type `String`
  """
  industry: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`location` of type `String`
  """
  location: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`website` of type `String`
  """
  website: OrderDirection
  """
  ✨ Generated from Field `BusinessProfile`.`workspaceId` of type `UUID!`
  """
  workspaceId: OrderDirection
}
"""
✨ Generated data input type for table 'LLMKey'. It includes all necessary fields for creating or upserting rows into table.
"""
input LLMKey_Data {
  """
  ✨ Generated from Field `LLMKey`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `LLMKey`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `LLMKey`.`config` of type `String`
  """
  config: String
  """
  ✨ `_expr` server value variant of `config` (✨ Generated from Field `LLMKey`.`config` of type `String`)
  """
  config_expr: String_Expr
  """
  ✨ Generated from Field `LLMKey`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `LLMKey`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `LLMKey`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `LLMKey`.`encryptedKey` of type `String`
  """
  encryptedKey: String
  """
  ✨ `_expr` server value variant of `encryptedKey` (✨ Generated from Field `LLMKey`.`encryptedKey` of type `String`)
  """
  encryptedKey_expr: String_Expr
  """
  ✨ Generated from Field `LLMKey`.`encryptionIV` of type `String`
  """
  encryptionIV: String
  """
  ✨ `_expr` server value variant of `encryptionIV` (✨ Generated from Field `LLMKey`.`encryptionIV` of type `String`)
  """
  encryptionIV_expr: String_Expr
  """
  ✨ Generated from Field `LLMKey`.`entityId` of type `String!`
  """
  entityId: String
  """
  ✨ `_expr` server value variant of `entityId` (✨ Generated from Field `LLMKey`.`entityId` of type `String!`)
  """
  entityId_expr: String_Expr
  """
  ✨ Generated from Field `LLMKey`.`entityType` of type `String!`
  """
  entityType: String
  """
  ✨ `_expr` server value variant of `entityType` (✨ Generated from Field `LLMKey`.`entityType` of type `String!`)
  """
  entityType_expr: String_Expr
  """
  ✨ Generated from Field `LLMKey`.`provider` of type `String!`
  """
  provider: String
  """
  ✨ `_expr` server value variant of `provider` (✨ Generated from Field `LLMKey`.`provider` of type `String!`)
  """
  provider_expr: String_Expr
  """
  ✨ Generated from Field `LLMKey`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `LLMKey`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `LLMKey`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
}
"""
✨ Generated filter input type for table 'LLMKey'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input LLMKey_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [LLMKey_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: LLMKey_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [LLMKey_Filter!]
  """
  ✨ Generated from Field `LLMKey`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `LLMKey`.`config` of type `String`
  """
  config: String_Filter
  """
  ✨ Generated from Field `LLMKey`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `LLMKey`.`encryptedKey` of type `String`
  """
  encryptedKey: String_Filter
  """
  ✨ Generated from Field `LLMKey`.`encryptionIV` of type `String`
  """
  encryptionIV: String_Filter
  """
  ✨ Generated from Field `LLMKey`.`entityId` of type `String!`
  """
  entityId: String_Filter
  """
  ✨ Generated from Field `LLMKey`.`entityType` of type `String!`
  """
  entityType: String_Filter
  """
  ✨ Generated from Field `LLMKey`.`provider` of type `String!`
  """
  provider: String_Filter
  """
  ✨ Generated from Field `LLMKey`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'LLMKey'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input LLMKey_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [LLMKey_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: LLMKey_Filter
}
"""
✨ Generated key input type for table 'LLMKey'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input LLMKey_Key {
  """
  ✨ Generated from Field `LLMKey`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `LLMKey`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'LLMKey'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input LLMKey_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: LLMKey_Filter
}
"""
✨ Generated order input type for table 'LLMKey'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input LLMKey_Order {
  """
  ✨ Generated from Field `LLMKey`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`config` of type `String`
  """
  config: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`encryptedKey` of type `String`
  """
  encryptedKey: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`encryptionIV` of type `String`
  """
  encryptionIV: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`entityId` of type `String!`
  """
  entityId: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`entityType` of type `String!`
  """
  entityType: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`provider` of type `String!`
  """
  provider: OrderDirection
  """
  ✨ Generated from Field `LLMKey`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
}
"""
✨ Generated data input type for table 'PartnerPreferences'. It includes all necessary fields for creating or upserting rows into table.
"""
input PartnerPreferences_Data {
  """
  ✨ Generated from Field `PartnerPreferences`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `PartnerPreferences`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `PartnerPreferences`.`combinedEmbedding` of type `Vector`
  """
  combinedEmbedding: Vector
  """
  ✨ `_embed` server value variant of `combinedEmbedding` (✨ Generated from Field `PartnerPreferences`.`combinedEmbedding` of type `Vector`)
  """
  combinedEmbedding_embed: Vector_Embed
  """
  ✨ Generated from Field `PartnerPreferences`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `PartnerPreferences`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `PartnerPreferences`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `PartnerPreferences`.`industries` of type `[String]`
  """
  industries: [String!]
  """
  ✨ Generated from Field `PartnerPreferences`.`locations` of type `[String]`
  """
  locations: [String!]
  """
  ✨ Generated from Field `PartnerPreferences`.`maxEmployeeCount` of type `Int`
  """
  maxEmployeeCount: Int
  """
  ✨ Generated from Field `PartnerPreferences`.`minEmployeeCount` of type `Int`
  """
  minEmployeeCount: Int
  """
  ✨ Generated from Field `PartnerPreferences`.`skillsNeeded` of type `[String]`
  """
  skillsNeeded: [String!]
  """
  ✨ Generated from Field `PartnerPreferences`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `PartnerPreferences`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `PartnerPreferences`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `PartnerPreferences`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `PartnerPreferences`.`workspaceId` of type `UUID!`)
  """
  workspaceId_expr: UUID_Expr
}
"""
✨ Generated filter input type for table 'PartnerPreferences'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input PartnerPreferences_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [PartnerPreferences_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: PartnerPreferences_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [PartnerPreferences_Filter!]
  """
  ✨ Generated from Field `PartnerPreferences`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `PartnerPreferences`.`combinedEmbedding` of type `Vector`
  """
  combinedEmbedding: Vector_Filter
  """
  ✨ Generated from Field `PartnerPreferences`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `PartnerPreferences`.`industries` of type `[String]`
  """
  industries: String_ListFilter
  """
  ✨ Generated from Field `PartnerPreferences`.`locations` of type `[String]`
  """
  locations: String_ListFilter
  """
  ✨ Generated from Field `PartnerPreferences`.`maxEmployeeCount` of type `Int`
  """
  maxEmployeeCount: Int_Filter
  """
  ✨ Generated from Field `PartnerPreferences`.`minEmployeeCount` of type `Int`
  """
  minEmployeeCount: Int_Filter
  """
  ✨ Generated from Field `PartnerPreferences`.`skillsNeeded` of type `[String]`
  """
  skillsNeeded: String_ListFilter
  """
  ✨ Generated from Field `PartnerPreferences`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `PartnerPreferences`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID_Filter
}
"""
✨ Generated first-row input type for table 'PartnerPreferences'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input PartnerPreferences_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [PartnerPreferences_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: PartnerPreferences_Filter
}
"""
✨ Generated key input type for table 'PartnerPreferences'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input PartnerPreferences_Key {
  """
  ✨ Generated from Field `PartnerPreferences`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `PartnerPreferences`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'PartnerPreferences'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input PartnerPreferences_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: PartnerPreferences_Filter
}
"""
✨ Generated order input type for table 'PartnerPreferences'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input PartnerPreferences_Order {
  """
  ✨ Generated from Field `PartnerPreferences`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `PartnerPreferences`.`combinedEmbedding` of type `Vector`
  """
  combinedEmbedding: OrderDirection
  """
  ✨ Generated from Field `PartnerPreferences`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `PartnerPreferences`.`maxEmployeeCount` of type `Int`
  """
  maxEmployeeCount: OrderDirection
  """
  ✨ Generated from Field `PartnerPreferences`.`minEmployeeCount` of type `Int`
  """
  minEmployeeCount: OrderDirection
  """
  ✨ Generated from Field `PartnerPreferences`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `PartnerPreferences`.`workspaceId` of type `UUID!`
  """
  workspaceId: OrderDirection
}
"""
✨ Generated data input type for table 'Profile'. It includes all necessary fields for creating or upserting rows into table.
"""
input Profile_Data {
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Profile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Profile`.`avatarUrl` of type `String`
  """
  avatarUrl: String
  """
  ✨ `_expr` server value variant of `avatarUrl` (✨ Generated from Field `Profile`.`avatarUrl` of type `String`)
  """
  avatarUrl_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`bio` of type `String`
  """
  bio: String
  """
  ✨ `_expr` server value variant of `bio` (✨ Generated from Field `Profile`.`bio` of type `String`)
  """
  bio_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`bioEmbedding` of type `Vector`
  """
  bioEmbedding: Vector
  """
  ✨ `_embed` server value variant of `bioEmbedding` (✨ Generated from Field `Profile`.`bioEmbedding` of type `Vector`)
  """
  bioEmbedding_embed: Vector_Embed
  """
  ✨ Generated from Field `Profile`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Profile`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Profile`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `Profile`.`interests` of type `[String]`
  """
  interests: [String!]
  """
  ✨ Generated from Field `Profile`.`isDefault` of type `Boolean!`
  """
  isDefault: Boolean
  """
  ✨ Generated from Field `Profile`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Profile`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`skills` of type `[String]`
  """
  skills: [String!]
  """
  ✨ Generated from Field `Profile`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Profile`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Profile`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `Profile`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Profile`.`userId` of type `String!`)
  """
  userId_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Profile'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Profile_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Profile_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Profile_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Profile_Filter!]
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Profile`.`avatarUrl` of type `String`
  """
  avatarUrl: String_Filter
  """
  ✨ Generated from Field `Profile`.`bio` of type `String`
  """
  bio: String_Filter
  """
  ✨ Generated from Field `Profile`.`bioEmbedding` of type `Vector`
  """
  bioEmbedding: Vector_Filter
  """
  ✨ Generated from Field `Profile`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Profile`.`interests` of type `[String]`
  """
  interests: String_ListFilter
  """
  ✨ Generated from Field `Profile`.`isDefault` of type `Boolean!`
  """
  isDefault: Boolean_Filter
  """
  ✨ Generated from Field `Profile`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Profile`.`skills` of type `[String]`
  """
  skills: String_ListFilter
  """
  ✨ Generated from Field `Profile`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Profile`.`userId` of type `String!`
  """
  userId: String_Filter
  """
  ✨ Generated from Field `Profile`.`workspaceMembers_on_profile` of type `[WorkspaceMember!]!`
  """
  workspaceMembers_on_profile: WorkspaceMember_ListFilter
}
"""
✨ Generated first-row input type for table 'Profile'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Profile_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Profile_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Profile_Filter
}
"""
✨ Generated key input type for table 'Profile'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Profile_Key {
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Profile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Profile'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Profile_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Profile_Filter
}
"""
✨ Generated order input type for table 'Profile'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Profile_Order {
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Profile`.`avatarUrl` of type `String`
  """
  avatarUrl: OrderDirection
  """
  ✨ Generated from Field `Profile`.`bio` of type `String`
  """
  bio: OrderDirection
  """
  ✨ Generated from Field `Profile`.`bioEmbedding` of type `Vector`
  """
  bioEmbedding: OrderDirection
  """
  ✨ Generated from Field `Profile`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Profile`.`isDefault` of type `Boolean!`
  """
  isDefault: OrderDirection
  """
  ✨ Generated from Field `Profile`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Profile`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Profile`.`userId` of type `String!`
  """
  userId: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `String!`)
  """
  id_expr: String_Expr
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `User`.`displayName` of type `String`
  """
  displayName: String
  """
  ✨ `_expr` server value variant of `displayName` (✨ Generated from Field `User`.`displayName` of type `String`)
  """
  displayName_expr: String_Expr
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String!`)
  """
  email_expr: String_Expr
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String
  """
  ✨ `_expr` server value variant of `photoUrl` (✨ Generated from Field `User`.`photoUrl` of type `String`)
  """
  photoUrl_expr: String_Expr
  """
  ✨ Generated from Field `User`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `User`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `User`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`displayName` of type `String`
  """
  displayName: String_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String_Filter
  """
  ✨ Generated from Field `User`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`workspaceMembers_on_user` of type `[WorkspaceMember!]!`
  """
  workspaceMembers_on_user: WorkspaceMember_ListFilter
  """
  ✨ Generated from Field `User`.`workspaceUsers_on_user` of type `[WorkspaceUser!]!`
  """
  workspaceUsers_on_user: WorkspaceUser_ListFilter
  """
  ✨ Generated from Field `User`.`workspaces_via_WorkspaceMember` of type `[Workspace!]!`
  """
  workspaces_via_WorkspaceMember: Workspace_ListFilter
  """
  ✨ Generated from Field `User`.`workspaces_via_WorkspaceUser` of type `[Workspace!]!`
  """
  workspaces_via_WorkspaceUser: Workspace_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `String!`)
  """
  id_expr: String_Expr
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName` of type `String`
  """
  displayName: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: OrderDirection
  """
  ✨ Generated from Field `User`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
}
"""
✨ Generated data input type for table 'Workspace'. It includes all necessary fields for creating or upserting rows into table.
"""
input Workspace_Data {
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Workspace`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `Workspace`.`createdBy` of type `String!`
  """
  createdBy: String
  """
  ✨ `_expr` server value variant of `createdBy` (✨ Generated from Field `Workspace`.`createdBy` of type `String!`)
  """
  createdBy_expr: String_Expr
  """
  ✨ Generated from Field `Workspace`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Workspace`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Workspace`.`logoUrl` of type `String`
  """
  logoUrl: String
  """
  ✨ `_expr` server value variant of `logoUrl` (✨ Generated from Field `Workspace`.`logoUrl` of type `String`)
  """
  logoUrl_expr: String_Expr
  """
  ✨ Generated from Field `Workspace`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Workspace`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `Workspace`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Workspace`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Workspace`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
}
"""
✨ Generated filter input type for table 'Workspace'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Workspace_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Workspace_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Workspace_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Workspace_Filter!]
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Workspace`.`createdBy` of type `String!`
  """
  createdBy: String_Filter
  """
  ✨ Generated from Field `Workspace`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Workspace`.`logoUrl` of type `String`
  """
  logoUrl: String_Filter
  """
  ✨ Generated from Field `Workspace`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Workspace`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Workspace`.`workspaceMembers_on_workspace` of type `[WorkspaceMember!]!`
  """
  workspaceMembers_on_workspace: WorkspaceMember_ListFilter
  """
  ✨ Generated from Field `Workspace`.`workspaceUsers_on_workspace` of type `[WorkspaceUser!]!`
  """
  workspaceUsers_on_workspace: WorkspaceUser_ListFilter
  """
  ✨ Generated from Field `Workspace`.`users_via_WorkspaceMember` of type `[User!]!`
  """
  users_via_WorkspaceMember: User_ListFilter
  """
  ✨ Generated from Field `Workspace`.`users_via_WorkspaceUser` of type `[User!]!`
  """
  users_via_WorkspaceUser: User_ListFilter
}
"""
✨ Generated first-row input type for table 'Workspace'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Workspace_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Workspace_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Workspace_Filter
}
"""
✨ Generated key input type for table 'Workspace'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Workspace_Key {
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Workspace`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Workspace'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Workspace_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Workspace_Filter
}
"""
✨ Generated order input type for table 'Workspace'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Workspace_Order {
  """
  ✨ Generated from Field `Workspace`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`createdBy` of type `String!`
  """
  createdBy: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`logoUrl` of type `String`
  """
  logoUrl: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Workspace`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
}
"""
✨ Generated data input type for table 'WorkspaceInvitation'. It includes all necessary fields for creating or upserting rows into table.
"""
input WorkspaceInvitation_Data {
  """
  ✨ Generated from Field `WorkspaceInvitation`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `WorkspaceInvitation`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `WorkspaceInvitation`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `WorkspaceInvitation`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `WorkspaceInvitation`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `WorkspaceInvitation`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `WorkspaceInvitation`.`email` of type `String!`)
  """
  email_expr: String_Expr
  """
  ✨ Generated from Field `WorkspaceInvitation`.`expiresAt` of type `Timestamp`
  """
  expiresAt: Timestamp
  """
  ✨ `_expr` server value variant of `expiresAt` (✨ Generated from Field `WorkspaceInvitation`.`expiresAt` of type `Timestamp`)
  """
  expiresAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `expiresAt` (✨ Generated from Field `WorkspaceInvitation`.`expiresAt` of type `Timestamp`)
  """
  expiresAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `WorkspaceInvitation`.`invitedBy` of type `String!`
  """
  invitedBy: String
  """
  ✨ `_expr` server value variant of `invitedBy` (✨ Generated from Field `WorkspaceInvitation`.`invitedBy` of type `String!`)
  """
  invitedBy_expr: String_Expr
  """
  ✨ Generated from Field `WorkspaceInvitation`.`role` of type `String!`
  """
  role: String
  """
  ✨ `_expr` server value variant of `role` (✨ Generated from Field `WorkspaceInvitation`.`role` of type `String!`)
  """
  role_expr: String_Expr
  """
  ✨ Generated from Field `WorkspaceInvitation`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `WorkspaceInvitation`.`status` of type `String!`)
  """
  status_expr: String_Expr
  """
  ✨ Generated from Field `WorkspaceInvitation`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `WorkspaceInvitation`.`workspaceId` of type `UUID!`)
  """
  workspaceId_expr: UUID_Expr
}
"""
✨ Generated filter input type for table 'WorkspaceInvitation'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input WorkspaceInvitation_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [WorkspaceInvitation_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: WorkspaceInvitation_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [WorkspaceInvitation_Filter!]
  """
  ✨ Generated from Field `WorkspaceInvitation`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `WorkspaceInvitation`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `WorkspaceInvitation`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `WorkspaceInvitation`.`expiresAt` of type `Timestamp`
  """
  expiresAt: Timestamp_Filter
  """
  ✨ Generated from Field `WorkspaceInvitation`.`invitedBy` of type `String!`
  """
  invitedBy: String_Filter
  """
  ✨ Generated from Field `WorkspaceInvitation`.`role` of type `String!`
  """
  role: String_Filter
  """
  ✨ Generated from Field `WorkspaceInvitation`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `WorkspaceInvitation`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID_Filter
}
"""
✨ Generated first-row input type for table 'WorkspaceInvitation'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input WorkspaceInvitation_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [WorkspaceInvitation_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: WorkspaceInvitation_Filter
}
"""
✨ Generated key input type for table 'WorkspaceInvitation'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input WorkspaceInvitation_Key {
  """
  ✨ Generated from Field `WorkspaceInvitation`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `WorkspaceInvitation`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'WorkspaceInvitation'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input WorkspaceInvitation_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: WorkspaceInvitation_Filter
}
"""
✨ Generated order input type for table 'WorkspaceInvitation'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input WorkspaceInvitation_Order {
  """
  ✨ Generated from Field `WorkspaceInvitation`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `WorkspaceInvitation`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `WorkspaceInvitation`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `WorkspaceInvitation`.`expiresAt` of type `Timestamp`
  """
  expiresAt: OrderDirection
  """
  ✨ Generated from Field `WorkspaceInvitation`.`invitedBy` of type `String!`
  """
  invitedBy: OrderDirection
  """
  ✨ Generated from Field `WorkspaceInvitation`.`role` of type `String!`
  """
  role: OrderDirection
  """
  ✨ Generated from Field `WorkspaceInvitation`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `WorkspaceInvitation`.`workspaceId` of type `UUID!`
  """
  workspaceId: OrderDirection
}
"""
✨ Generated data input type for table 'WorkspaceMember'. It includes all necessary fields for creating or upserting rows into table.
"""
input WorkspaceMember_Data {
  """
  ✨ Generated from Field `WorkspaceMember`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `WorkspaceMember`.`workspaceId` of type `UUID!`)
  """
  workspaceId_expr: UUID_Expr
  """
  ✨ Generated from Field `WorkspaceMember`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `WorkspaceMember`.`userId` of type `String!`)
  """
  userId_expr: String_Expr
  """
  ✨ Generated from Field `WorkspaceMember`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `WorkspaceMember`.`workspace` of type `Workspace!`
  """
  workspace: Workspace_Key
  """
  ✨ Generated from Field `WorkspaceMember`.`profileId` of type `UUID`
  """
  profileId: UUID
  """
  ✨ `_expr` server value variant of `profileId` (✨ Generated from Field `WorkspaceMember`.`profileId` of type `UUID`)
  """
  profileId_expr: UUID_Expr
  """
  ✨ Generated from Field `WorkspaceMember`.`profile` of type `Profile`
  """
  profile: Profile_Key
  """
  ✨ Generated from Field `WorkspaceMember`.`joinedAt` of type `Timestamp!`
  """
  joinedAt: Timestamp
  """
  ✨ `_expr` server value variant of `joinedAt` (✨ Generated from Field `WorkspaceMember`.`joinedAt` of type `Timestamp!`)
  """
  joinedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `joinedAt` (✨ Generated from Field `WorkspaceMember`.`joinedAt` of type `Timestamp!`)
  """
  joinedAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `WorkspaceMember`.`role` of type `String!`
  """
  role: String
  """
  ✨ `_expr` server value variant of `role` (✨ Generated from Field `WorkspaceMember`.`role` of type `String!`)
  """
  role_expr: String_Expr
}
"""
✨ Generated filter input type for table 'WorkspaceMember'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input WorkspaceMember_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [WorkspaceMember_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: WorkspaceMember_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [WorkspaceMember_Filter!]
  """
  ✨ Generated from Field `WorkspaceMember`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID_Filter
  """
  ✨ Generated from Field `WorkspaceMember`.`userId` of type `String!`
  """
  userId: String_Filter
  """
  ✨ Generated from Field `WorkspaceMember`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `WorkspaceMember`.`workspace` of type `Workspace!`
  """
  workspace: Workspace_Filter
  """
  ✨ Generated from Field `WorkspaceMember`.`profileId` of type `UUID`
  """
  profileId: UUID_Filter
  """
  ✨ Generated from Field `WorkspaceMember`.`profile` of type `Profile`
  """
  profile: Profile_Filter
  """
  ✨ Generated from Field `WorkspaceMember`.`joinedAt` of type `Timestamp!`
  """
  joinedAt: Timestamp_Filter
  """
  ✨ Generated from Field `WorkspaceMember`.`role` of type `String!`
  """
  role: String_Filter
}
"""
✨ Generated first-row input type for table 'WorkspaceMember'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input WorkspaceMember_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [WorkspaceMember_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: WorkspaceMember_Filter
}
"""
✨ Generated key input type for table 'WorkspaceMember'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input WorkspaceMember_Key {
  """
  ✨ Generated from Field `WorkspaceMember`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `WorkspaceMember`.`workspaceId` of type `UUID!`)
  """
  workspaceId_expr: UUID_Expr
  """
  ✨ Generated from Field `WorkspaceMember`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `WorkspaceMember`.`userId` of type `String!`)
  """
  userId_expr: String_Expr
}
"""
✨ Generated list filter input type for table 'WorkspaceMember'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input WorkspaceMember_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: WorkspaceMember_Filter
}
"""
✨ Generated order input type for table 'WorkspaceMember'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input WorkspaceMember_Order {
  """
  ✨ Generated from Field `WorkspaceMember`.`workspaceId` of type `UUID!`
  """
  workspaceId: OrderDirection
  """
  ✨ Generated from Field `WorkspaceMember`.`userId` of type `String!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `WorkspaceMember`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `WorkspaceMember`.`workspace` of type `Workspace!`
  """
  workspace: Workspace_Order
  """
  ✨ Generated from Field `WorkspaceMember`.`profileId` of type `UUID`
  """
  profileId: OrderDirection
  """
  ✨ Generated from Field `WorkspaceMember`.`profile` of type `Profile`
  """
  profile: Profile_Order
  """
  ✨ Generated from Field `WorkspaceMember`.`joinedAt` of type `Timestamp!`
  """
  joinedAt: OrderDirection
  """
  ✨ Generated from Field `WorkspaceMember`.`role` of type `String!`
  """
  role: OrderDirection
}
"""
✨ Generated data input type for table 'WorkspaceUser'. It includes all necessary fields for creating or upserting rows into table.
"""
input WorkspaceUser_Data {
  """
  ✨ Generated from Field `WorkspaceUser`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `WorkspaceUser`.`workspaceId` of type `UUID!`)
  """
  workspaceId_expr: UUID_Expr
  """
  ✨ Generated from Field `WorkspaceUser`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `WorkspaceUser`.`userId` of type `String!`)
  """
  userId_expr: String_Expr
  """
  ✨ Generated from Field `WorkspaceUser`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `WorkspaceUser`.`workspace` of type `Workspace!`
  """
  workspace: Workspace_Key
  """
  ✨ Generated from Field `WorkspaceUser`.`joinedAt` of type `Timestamp!`
  """
  joinedAt: Timestamp
  """
  ✨ `_expr` server value variant of `joinedAt` (✨ Generated from Field `WorkspaceUser`.`joinedAt` of type `Timestamp!`)
  """
  joinedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `joinedAt` (✨ Generated from Field `WorkspaceUser`.`joinedAt` of type `Timestamp!`)
  """
  joinedAt_time: Timestamp_Relative
  """
  ✨ Generated from Field `WorkspaceUser`.`role` of type `String!`
  """
  role: String
  """
  ✨ `_expr` server value variant of `role` (✨ Generated from Field `WorkspaceUser`.`role` of type `String!`)
  """
  role_expr: String_Expr
}
"""
✨ Generated filter input type for table 'WorkspaceUser'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input WorkspaceUser_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [WorkspaceUser_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: WorkspaceUser_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [WorkspaceUser_Filter!]
  """
  ✨ Generated from Field `WorkspaceUser`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID_Filter
  """
  ✨ Generated from Field `WorkspaceUser`.`userId` of type `String!`
  """
  userId: String_Filter
  """
  ✨ Generated from Field `WorkspaceUser`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `WorkspaceUser`.`workspace` of type `Workspace!`
  """
  workspace: Workspace_Filter
  """
  ✨ Generated from Field `WorkspaceUser`.`joinedAt` of type `Timestamp!`
  """
  joinedAt: Timestamp_Filter
  """
  ✨ Generated from Field `WorkspaceUser`.`role` of type `String!`
  """
  role: String_Filter
}
"""
✨ Generated first-row input type for table 'WorkspaceUser'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input WorkspaceUser_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [WorkspaceUser_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: WorkspaceUser_Filter
}
"""
✨ Generated key input type for table 'WorkspaceUser'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input WorkspaceUser_Key {
  """
  ✨ Generated from Field `WorkspaceUser`.`workspaceId` of type `UUID!`
  """
  workspaceId: UUID
  """
  ✨ `_expr` server value variant of `workspaceId` (✨ Generated from Field `WorkspaceUser`.`workspaceId` of type `UUID!`)
  """
  workspaceId_expr: UUID_Expr
  """
  ✨ Generated from Field `WorkspaceUser`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `WorkspaceUser`.`userId` of type `String!`)
  """
  userId_expr: String_Expr
}
"""
✨ Generated list filter input type for table 'WorkspaceUser'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input WorkspaceUser_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: WorkspaceUser_Filter
}
"""
✨ Generated order input type for table 'WorkspaceUser'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input WorkspaceUser_Order {
  """
  ✨ Generated from Field `WorkspaceUser`.`workspaceId` of type `UUID!`
  """
  workspaceId: OrderDirection
  """
  ✨ Generated from Field `WorkspaceUser`.`userId` of type `String!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `WorkspaceUser`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `WorkspaceUser`.`workspace` of type `Workspace!`
  """
  workspace: Workspace_Order
  """
  ✨ Generated from Field `WorkspaceUser`.`joinedAt` of type `Timestamp!`
  """
  joinedAt: OrderDirection
  """
  ✨ Generated from Field `WorkspaceUser`.`role` of type `String!`
  """
  role: OrderDirection
}
