extend type Profile {
  """
  ✨ List `WorkspaceMember` objects in a one-to-many relationship (where `WorkspaceMember`.`profile` is this object).
  """
  workspaceMembers_on_profile(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [WorkspaceMember!]! @fdc_generated(from: "WorkspaceMember.profile", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
}
extend type User {
  """
  ✨ List `WorkspaceMember` objects in a one-to-many relationship (where `WorkspaceMember`.`user` is this object).
  """
  workspaceMembers_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [WorkspaceMember!]! @fdc_generated(from: "WorkspaceMember.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `WorkspaceUser` objects in a one-to-many relationship (where `WorkspaceUser`.`user` is this object).
  """
  workspaceUsers_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceUser_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceUser_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [WorkspaceUser!]! @fdc_generated(from: "WorkspaceUser.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Workspace` objects using `WorkspaceMember` as the join table (a `WorkspaceMember` object exists where its `user` is this and its `workspace` is that).
  """
  workspaces_via_WorkspaceMember(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Workspace!]! @fdc_generated(from: "WorkspaceMember", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  ✨ List `Workspace` objects using `WorkspaceUser` as the join table (a `WorkspaceUser` object exists where its `user` is this and its `workspace` is that).
  """
  workspaces_via_WorkspaceUser(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceUser_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceUser_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Workspace!]! @fdc_generated(from: "WorkspaceUser", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
}
extend type Workspace {
  """
  ✨ List `WorkspaceMember` objects in a one-to-many relationship (where `WorkspaceMember`.`workspace` is this object).
  """
  workspaceMembers_on_workspace(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [WorkspaceMember!]! @fdc_generated(from: "WorkspaceMember.workspace", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `WorkspaceUser` objects in a one-to-many relationship (where `WorkspaceUser`.`workspace` is this object).
  """
  workspaceUsers_on_workspace(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceUser_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceUser_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [WorkspaceUser!]! @fdc_generated(from: "WorkspaceUser.workspace", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects using `WorkspaceMember` as the join table (a `WorkspaceMember` object exists where its `workspace` is this and its `user` is that).
  """
  users_via_WorkspaceMember(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [User!]! @fdc_generated(from: "WorkspaceMember", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  ✨ List `User` objects using `WorkspaceUser` as the join table (a `WorkspaceUser` object exists where its `workspace` is this and its `user` is that).
  """
  users_via_WorkspaceUser(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkspaceUser_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkspaceUser_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [User!]! @fdc_generated(from: "WorkspaceUser", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
}
